### ISSUE TITLE
Include :: "Sequence contains more than one matching element" thrown in some cases of multi level include

### ISSUE THREAD

**Issue by maumar** [aspnet/EntityFramework#1460]
Repro:

```
    public class Level1
    {
        public int Id { get; set; }
        public string Name { get; set; }

        public ICollection<Level2> OneToMany_Optional { get; set; }
    }

    public class Level2
    {
        public int Id { get; set; }
        public string Name { get; set; }

        public int Level1_Required_Id { get; set; }
        public int? Level1_Optional_Id { get; set; }

        public ICollection<Level3> OneToMany_Optional { get; set; }
        public Level1 OneToMany_Optional_Inverse { get; set; }
    }

    public class Level3
    {
        public int Id { get; set; }
        public string Name { get; set; }

        public int Level2_Required_Id { get; set; }
        public int? Level2_Optional_Id { get; set; }

        public ICollection<Level4> OneToMany_Optional { get; set; }

        public Level2 OneToMany_Optional_Inverse { get; set; }
    }

    public class Level4
    {
        public int Id { get; set; }
        public string Name { get; set; }

        public int Level3_Required_Id { get; set; }
        public int? Level3_Optional_Id { get; set; }

        public Level3 OneToMany_Optional_Inverse { get; set; }
    }


    public class MyContext : DbContext
    {
        public DbSet<Level1> LevelOne { get; set; }
        public DbSet<Level2> LevelTwo { get; set; }
        public DbSet<Level3> LevelThree { get; set; }
        public DbSet<Level4> LevelFour { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.Entity<Level1>().Property(e => e.Id).GenerateValueOnAdd(false);
            modelBuilder.Entity<Level2>().Property(e => e.Id).GenerateValueOnAdd(false);

            modelBuilder.Entity<Level1>().HasMany(e => e.OneToMany_Optional).WithOne(e => e.OneToMany_Optional_Inverse).Required(false);

            modelBuilder.Entity<Level2>().Property(e => e.Id).GenerateValueOnAdd(false);
            modelBuilder.Entity<Level2>().Property(e => e.Id).GenerateValueOnAdd(false);

            modelBuilder.Entity<Level2>().HasMany(e => e.OneToMany_Optional).WithOne(e => e.OneToMany_Optional_Inverse).Required(false);

            modelBuilder.Entity<Level3>().Property(e => e.Id).GenerateValueOnAdd(false);
            modelBuilder.Entity<Level3>().Property(e => e.Id).GenerateValueOnAdd(false);

            modelBuilder.Entity<Level3>().HasMany(e => e.OneToMany_Optional).WithOne(e => e.OneToMany_Optional_Inverse).Required(false);

            modelBuilder.Entity<Level4>().Property(e => e.Id).GenerateValueOnAdd(false);
            modelBuilder.Entity<Level4>().Property(e => e.Id).GenerateValueOnAdd(false);
        }

        protected override void OnConfiguring(DbContextOptions options)
        {
            options.UseSqlServer(new SqlConnectionStringBuilder { DataSource = ".", InitialCatalog = "Repro1460", MultipleActiveResultSets = true, IntegratedSecurity = true }.ToString());
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            using (var ctx = new MyContext())
            {
                ctx.Database.EnsureDeleted();
                ctx.Database.EnsureCreated();

                var l1_01 = new Level1 { Id = 1, Name = "L1 01", };
                var l1_02 = new Level1 { Id = 2, Name = "L1 02", };
                var l1_03 = new Level1 { Id = 3, Name = "L1 03", };

                var l2_01 = new Level2 { Id = 1, Name = "L2 01", };
                var l2_02 = new Level2 { Id = 2, Name = "L2 02", };
                var l2_03 = new Level2 { Id = 3, Name = "L2 03", };

                var l3_01 = new Level3 { Id = 1, Name = "L3 01", };
                var l3_02 = new Level3 { Id = 2, Name = "L3 02", };
                var l3_03 = new Level3 { Id = 3, Name = "L3 03", };

                var l4_01 = new Level4 { Id = 1, Name = "L4 01", };
                var l4_02 = new Level4 { Id = 2, Name = "L4 02", };
                var l4_03 = new Level4 { Id = 3, Name = "L4 03", };

                var l1s = new[] { l1_01, l1_02, l1_03 }.ToArray();
                var l2s = new[] { l2_01, l2_02, l2_03 }.ToArray();
                var l3s = new[] { l3_01, l3_02, l3_03 }.ToArray();
                var l4s = new[] { l4_01, l4_02, l4_03 }.ToArray();

                ctx.LevelOne.Add(l1s);
                ctx.LevelTwo.Add(l2s);
                ctx.LevelThree.Add(l3s);
                ctx.LevelFour.Add(l4s);

                ctx.SaveChanges();

                l1s[0].OneToMany_Optional = new List<Level2> { l2s[1] };

                l2s[0].OneToMany_Optional = new List<Level3> { l3s[1] };

                l3s[0].OneToMany_Optional = new List<Level4> { l4s[1] };

                ctx.SaveChanges();
            }

            using (var ctx = new MyContext())
            {
                ctx.LevelOne.Include(e => e.OneToMany_Optional).ThenInclude(e => e.OneToMany_Optional).ThenInclude(e => e.OneToMany_Optional_Inverse).ThenInclude(e => e.OneToMany_Optional).ToList();
            }
        }
    }
```

throws:

Unhandled Exception: System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predic
ate)
   at Microsoft.Data.Entity.Relational.Query.ExpressionTreeVisitors.IncludeExpre
ssionTreeVisitor.BuildColumnExpression(IReadOnlyCollection`1 projections, TableE
xpressionBase tableExpression, IProperty property)
   at Microsoft.Data.Entity.Relational.Query.ExpressionTreeVisitors.IncludeExpre
ssionTreeVisitor.BuildJoinEqualityExpression(INavigation navigation, IReadOnlyLi
st`1 primaryKeyProperties, TableExpressionBase targetTableExpression, TableExpre
ssionBase joinExpression)
   at Microsoft.Data.Entity.Relational.Query.ExpressionTreeVisitors.IncludeExpre
ssionTreeVisitor.<CreateIncludeRelatedValuesStrategyFactories>d__6.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Dynamic.Utils.CollectionExtensions.ToReadOnly[T](IEnumerable`1 enum
erable)
   at System.Linq.Expressions.Expression.NewArrayInit(Type type, IEnumerable`1 i
nitializers)
   at Microsoft.Data.Entity.Relational.Query.ExpressionTreeVisitors.IncludeExpre
ssionTreeVisitor.VisitMethodCallExpression(MethodCallExpression expression)
   at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitExpression(Expression exp
ression)
   at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitLambdaExpression(LambdaEx
pression expression)
   at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitExpression(Expression exp
ression)
   at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitAndConvert[T](T expressio
n, String methodName)
   at Remotion.Linq.Parsing.ExpressionTreeVisitor.<>c__DisplayClass6`1.<VisitAnd
Convert>b__5(T expression)
   at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitList[T](ReadOnlyCollectio
n`1 list, Func`2 visitMethod)
   at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitAndConvert[T](ReadOnlyCol
lection`1 expressions, String callerName)
   at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitMethodCallExpression(Meth
odCallExpression expression)
   at Microsoft.Data.Entity.Relational.Query.ExpressionTreeVisitors.IncludeExpre
ssionTreeVisitor.VisitMethodCallExpression(MethodCallExpression expression)
   at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitExpression(Expression exp
ression)
   at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitAndConvert[T](T expressio
n, String methodName)
   at Remotion.Linq.Parsing.ExpressionTreeVisitor.<>c__DisplayClass6`1.<VisitAnd
Convert>b__5(T expression)
   at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitList[T](ReadOnlyCollectio
n`1 list, Func`2 visitMethod)
   at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitAndConvert[T](ReadOnlyCol
lection`1 expressions, String callerName)
   at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitMethodCallExpression(Meth
odCallExpression expression)
   at Microsoft.Data.Entity.Relational.Query.ExpressionTreeVisitors.IncludeExpre
ssionTreeVisitor.VisitMethodCallExpression(MethodCallExpression expression)
   at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitExpression(Expression exp
ression)
   at Microsoft.Data.Entity.Relational.Query.RelationalQueryModelVisitor.Include
Navigations(IQuerySource querySource, Type resultType, LambdaExpression accessor
Lambda, IReadOnlyList`1 navigationPath)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.IncludeNavigations(Que
ryModel queryModel, Type resultType)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.CreateQueryExecutor[TR
esult](QueryModel queryModel)
   at Microsoft.Data.Entity.Relational.RelationalDataStore.Query[TResult](QueryM
odel queryModel)
   at Microsoft.Data.Entity.Query.EntityQueryExecutor.ExecuteCollection[T](Query
Model queryModel)
   at Remotion.Linq.Clauses.StreamedData.StreamedSequenceInfo.ExecuteCollectionQ
ueryModel[T](QueryModel queryModel, IQueryExecutor executor)
   at Remotion.Linq.Clauses.StreamedData.StreamedSequenceInfo.ExecuteQueryModel(
QueryModel queryModel, IQueryExecutor executor)
   at Remotion.Linq.QueryModel.Execute(IQueryExecutor executor)
   at Remotion.Linq.QueryProviderBase.Execute(Expression expression)
   at Remotion.Linq.QueryProviderBase.System.Linq.IQueryProvider.Execute[TResult
](Expression expression)
   at Remotion.Linq.QueryableBase`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Repro1460.Program.Main(String[] args) in D:\Projects\Repro1460\Repro1460\P
rogram.cs:line 138

**Comment by rowanmiller** [comment]
__EF Team Triage:__ _This issue is lacking enough information for us to be able to effectively triage it. For a guide on submitting good bug reports, read_ [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html). _The most important elements to help us act on a bug report are example code/steps that reproduce the issue, the outcome/results you are expecting, and the results or error message that you are receiving._

**Comment by rowanmiller** [comment]
:smiley:

**Comment by maumar** [comment]
i was too slow... ;)

**Comment by maumar** [comment]
fixed in 6d918d2472ace2a62fe3dfc83c897f5074a16fe2

**Comment by luisrudge** [comment]
Is this in beta3?

**Comment by maumar** [comment]
yes, this should be in beta3. Are you seeing this bug still?

**Comment by grandchamp** [comment]
@maumar I'm seeing this bug still. Should i open a new issue or post here?

**Comment by luisrudge** [comment]
Yeah. I asked because I had this problem too (with beta 3)

**Comment by maumar** [comment]
Few people reported this. Let me reopen this one and clean up all the other ones

**Comment by grandchamp** [comment]
Model

```
 public class Perfil
    {
        public int Id { get; set; }

        public int ApplicationUserId { get; set; }
        public virtual ApplicationUser ApplicationUser { get; set; }
        ...
    }
```

Query that throws "Sequence contains more than one element"
```
 _db.Perfis.Include(x => x.ApplicationUser)
                 .Where(x => x.ApplicationUser.NormalizedUserName.Contains(searchBy))
                 .ToList()
```

If i just don't use any of the included object properties the query runs fine. Like this:
```
_db.Perfis.Include(x => x.ApplicationUser)
                .Where(x => x.Nome.Contains(searchBy))
                .ToList();
```

**Comment by maumar** [comment]
Verified that this fix didn't get into beta-3 but i'ts fixed in current bits. Closing
