### ISSUE TITLE
Subquery.Where(Expression<Func<Entity, bool>>) throws exception

### ISSUE THREAD

**Issue by Tasteful** [aspnet/EntityFramework#3722]
When adding a subquery from expression an exception it thrown as below.
```
{
"message":"An error has occurred.",
"exceptionMessage":"Could not parse expression 'value(Microsoft.Data.Entity.Query.EntityQueryable`1[ProductEntity+FieldDataEntity]).Any(__expr_0)': The given arguments did not match the expected arguments: Object of type 'System.Linq.Expressions.TypedParameterExpression' cannot be converted to type 'System.Linq.Expressions.LambdaExpression'.",
"exceptionType":"System.NotSupportedException",
"stackTrace":"   at Remotion.Linq.Parsing.Structure.MethodCallExpressionParser.CreateExpressionNode(Type nodeType, MethodCallExpressionParseInfo parseInfo, Object[] additionalConstructorParameters)
   at Remotion.Linq.Parsing.Structure.MethodCallExpressionParser.Parse(String associatedIdentifier, IExpressionNode source, IEnumerable`1 arguments, MethodCallExpression expressionToParse)
   at Remotion.Linq.Parsing.Structure.ExpressionTreeParser.ParseMethodCallExpression(MethodCallExpression methodCallExpression, String associatedIdentifier)
   at Remotion.Linq.Parsing.Structure.QueryParser.GetParsedQuery(Expression expressionTreeRoot)
   at Remotion.Linq.Parsing.ExpressionVisitors.SubQueryFindingExpressionVisitor.Visit(Expression expression)
   at System.Linq.Expressions.ExpressionVisitor.VisitLambda[T](Expression`1 node)
   at Remotion.Linq.Parsing.ExpressionVisitors.SubQueryFindingExpressionVisitor.Visit(Expression expression)
   at Remotion.Linq.Parsing.Structure.MethodCallExpressionParser.ProcessArgumentExpression(Expression argumentExpression)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Remotion.Linq.Parsing.Structure.MethodCallExpressionParser.Parse(String associatedIdentifier, IExpressionNode source, IEnumerable`1 arguments, MethodCallExpression expressionToParse)
   at Remotion.Linq.Parsing.Structure.ExpressionTreeParser.ParseMethodCallExpression(MethodCallExpression methodCallExpression, String associatedIdentifier)
   at Remotion.Linq.Parsing.Structure.QueryParser.GetParsedQuery(Expression expressionTreeRoot)
   at Microsoft.Data.Entity.Query.QueryCompiler.<>c__DisplayClass16_0`1.<CompileQuery>b__0()
   at Microsoft.Data.Entity.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.Data.Entity.Query.QueryCompiler.Execute[TResult](Expression query)
   at Remotion.Linq.QueryableBase`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
}
```

Working subquery
```
var subQuery = _queryContext.Query<ProductEntity.FieldDataEntity>();
var query1 = _queryContext.Query<ProductEntity>().Where(x => subQuery.Any(z => z.Id == "id")).ToList();
```

Non working subquery
```
Expression<Func<ProductEntity.FieldDataEntity, bool>> expr = z => z.Id == "id";
var subQuery = _queryContext.Query<ProductEntity.FieldDataEntity>();
var query2 = _queryContext.Query<ProductEntity>().Where(x => subQuery.Any(expr)).ToList();
```

Entity in example looks like this
```
public class ProductEntity
{
    public ICollection<FieldDataEntity> FieldDatas { get; set; }
    public string Id { get; set; }

    public class FieldDataEntity
    {
        public string OwnerId { get; set; }
        public string Id { get; set; }
        public string Culture { get; set; }
        public string TextValue { get; set; }
    }
}
```
and mapping
```
builder.Entity<ProductEntity>(b =>
{
    b.ToTable("Product", "Products");
    b.HasKey(p => p.Id);
    b.Property(p => p.Id).HasMaxLength(100);

    b.HasMany(p => p.FieldDatas)
        .WithOne()
        .WillCascadeOnDelete()
        .ForeignKey(p => p.OwnerId);
});

builder.Entity<ProductEntity.FieldDataEntity>(b =>
{
    b.ToTable("ProductFieldData", "Products");
    b.HasKey(p => new { p.OwnerId, p.Id, p.Culture });
    b.Property(p => p.Id).HasMaxLength(100);
    b.Property(p => p.Culture).HasMaxLength(10);
});
```

I'm using beta8 version. Any chance that this is fixed in the RC1 version?

**Comment by Tasteful** [comment]
@rowanmiller or @anpete Any update for this issue?

**Comment by mikary** [comment]
Confirmed that this reproduces in beta8 but is working in current dev. Appears to have been resolved in #4431.

**Comment by mikebridge** [comment]
I have subquery that is generating that same error, but only when the Func is passed into the method containing the query.

```
    System.NotSupportedException : Could not parse expression 's.Programs.Where(__StartsWith_0)': The given arguments did not match the expected arguments: Object of type 'System.Linq.Expressions.TypedParameterExpression' cannot be converted to type 'System.Linq.Expressions.LambdaExpression'.
```

I have a "School" entity which contains "Program" entities, and I'm doing a subquery like the following---and this works fine:

```c#
public IQueryable<SchoolResult> SearchShoolPrograms(
            Expression<Func<School, bool>> schoolExpression)
{
    return _dbContext.School
        .Where(schoolExpression)
        // ... 
        .Select(s => new SchoolResult
         {
             Name = s.Name,
             Programs = s.Programs.Where(p => p.Name == "Test")
                   .Select(p => new ProgramResult
                   {
                         Id = p.Id,
                         Name = p.Name,
                   });
         }
}

SearchShoolPrograms(school => school.Active);

```

However, I can't extract the "Where" function without generating an error.  I think this should work the same:

```
public IQueryable<SchoolResult> SearchShoolPrograms(
            Expression<Func<School, bool>> schoolExpression,
            Func<Program,bool> programExpression)
{
    return _dbContext.School
        .Where(schoolExpression)
        // ... 
        .Select(s => new SchoolResult
         {
             Name = s.Name,
             Programs = s.Programs.Where(programExpression)
                   .Select(p => new ProgramResult
                   {
                         Id = p.Id,
                         Name = p.Name,
                   });
         }
}

SearchSchoolPrograms (s=> s.Active, p => p.Name == "Test");
```

Any idea why these are different?  This is with EntityFrameworkCore 1.1.1.

**Comment by mikebridge** [comment]
I'm sure I'm missing something obvious here.  But it looks like I get the same error if I try to extract the Func from the Expression.  This works when I pass it into my `SearchShoolPrograms` method:

```c#
Expression<Func<School, bool>> expr = school => 
    school.Active && school.Programs.Any(program => program.Name.StartsWith("U"));
```

This doesn't:

```c#
Func<Program, bool> p = program => program.Name.StartsWith("U");
Expression<Func<School, bool>> expr = school => school.Active && school.Programs.Any(p);
```

I think they should be equivalent, but I'm still getting `System.NotSupportedException : Could not parse expression 'school.Programs.Any(__p_0)': The given arguments did not match the expected arguments: Object of type 'System.Linq.Expressions.TypedParameterExpression' cannot be converted to type 'System.Linq.Expressions.LambdaExpression'.`

**Comment by smitpatel** [comment]
@mikebridge - Can you post whole stacktrace?

**Comment by mikebridge** [comment]
@smitpatel sorry, yes, here it is:

```
System.NotSupportedException : Could not parse expression 'school.Programs.Any(__p_0)': The given arguments did not match the expected arguments: Object of type 'System.Linq.Expressions.TypedParameterExpression' cannot be converted to type 'System.Linq.Expressions.LambdaExpression'.
   at Remotion.Linq.Parsing.Structure.MethodCallExpressionParser.CreateExpressionNode(Type nodeType, MethodCallExpressionParseInfo parseInfo, Object[] additionalConstructorParameters)
   at Remotion.Linq.Parsing.Structure.MethodCallExpressionParser.Parse(String associatedIdentifier, IExpressionNode source, IEnumerable`1 arguments, MethodCallExpression expressionToParse)
   at Remotion.Linq.Parsing.Structure.ExpressionTreeParser.ParseMethodCallExpression(MethodCallExpression methodCallExpression, String associatedIdentifier)
   at Remotion.Linq.Parsing.Structure.ExpressionTreeParser.ParseTree(Expression expressionTree)
   at Remotion.Linq.Parsing.Structure.QueryParser.GetParsedQuery(Expression expressionTreeRoot)
   at Remotion.Linq.Parsing.ExpressionVisitors.SubQueryFindingExpressionVisitor.Visit(Expression expression)
   at System.Linq.Expressions.ExpressionVisitor.VisitBinary(BinaryExpression node)
   at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
   at Remotion.Linq.Parsing.ExpressionVisitors.SubQueryFindingExpressionVisitor.Visit(Expression expression)
   at System.Linq.Expressions.ExpressionVisitor.VisitLambda[T](Expression`1 node)
   at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
   at Remotion.Linq.Parsing.ExpressionVisitors.SubQueryFindingExpressionVisitor.Visit(Expression expression)
   at System.Linq.Enumerable.SelectListPartitionIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Remotion.Linq.Parsing.Structure.MethodCallExpressionParser.Parse(String associatedIdentifier, IExpressionNode source, IEnumerable`1 arguments, MethodCallExpression expressionToParse)
   at Remotion.Linq.Parsing.Structure.ExpressionTreeParser.ParseMethodCallExpression(MethodCallExpression methodCallExpression, String associatedIdentifier)
   at Remotion.Linq.Parsing.Structure.ExpressionTreeParser.ParseMethodCallExpression(MethodCallExpression methodCallExpression, String associatedIdentifier)
   at Remotion.Linq.Parsing.Structure.ExpressionTreeParser.ParseMethodCallExpression(MethodCallExpression methodCallExpression, String associatedIdentifier)
   at Remotion.Linq.Parsing.Structure.ExpressionTreeParser.ParseMethodCallExpression(MethodCallExpression methodCallExpression, String associatedIdentifier)
   at Remotion.Linq.Parsing.Structure.ExpressionTreeParser.ParseTree(Expression expressionTree)
   at Remotion.Linq.Parsing.Structure.QueryParser.GetParsedQuery(Expression expressionTreeRoot)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileAsyncQueryCore[TResult](Expression query, INodeTypeProvider nodeTypeProvider, IDatabase database)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.System.Collections.Generic.IAsyncEnumerable<TResult>.GetEnumerator()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.<ToListAsync>d__129`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ProgramManager.Services.ProgramMatchingService.<SearchSchoolPrograms>d__4.MoveNext() in C:\Visual Studio 2017\Projects\MyProject\src\ProgramManager\Services\ProgramMatchingService.cs:line 89
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ProgramManager.Tests.Integration.Services.ProgramMatchingServiceTests.<It_Should_Return>d__4.MoveNext() in C:\Visual Studio 2017\Projects\MyProject\test\ProgramManager.Tests.Integration\Services\ProgramMatchingServiceTests.cs:line 48
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by mikebridge** [comment]
@smitpatel If it helps, I created a [test project](https://github.com/mikebridge/EFQuestion) that generates the error with an in-memory db.

**Comment by smitpatel** [comment]
@mikebridge - I filed #8019 for your issue.

**Comment by mikebridge** [comment]
@smitpatel Thanks!
