### ISSUE TITLE
Base Query Filter (Defining Query)

### ISSUE THREAD

**Issue by AdrianHostettler** [aspnet/EntityFramework#5774]
Hy there, hope you're all doing well. ;)

This is a Feature Request.

I was wondering, if EF Core will support/implement a **Filtering** functionality for e.g. SoftDeletion configurable in a `CustomDbContext.OnModelCreating(ModelBuilder builder)` like this:

`builder.Filter<IBaseEntity>(e => e.Where(x => !x.IsSoftDeleted));`

Whereas `IBaseEntity` Interface ensures that the concerned models have the `IsSoftDeleted` property.

In addition it would also be nice, if this filter could be `turned on and off`, if e.g. i would need to access the deleted records for administration/historyview purposes.

There is a library from zzzprojects [EntityFramework-Plus](https://github.com/zzzprojects/EntityFramework-Plus/wiki/EF-Query-Filter-%7C-Entity-Framework-Dynamic-Instance-and-Global-Filters) that would support this in older versions of EF, but it would be nice, if the desired functionality would be working out of the box/native, without using that library.

The creators of EntityFramework-Plus note on their page, that 

> Entity Framework 7:
>     DOES NOT support filter by inheritance/interface (Will be supported when EntityFramework team will fix this issue: [https://github.com/aspnet/EntityFramework/issues/3736](https://github.com/aspnet/EntityFramework/issues/3736))

So i'd like to know, if we can expect this feature to be built in on 1.0.0 (Tools Preview 2) Milestone at 27 June 2016, or if this bug will be looked at, so that zzzprojects could bring out a new version of their libraries.

Please let me know what your plans are concerning that topic, I hope I'm not the only one, that would love that feature, otherwise i would probably have to do that filtering manually in all my Repositories/DAL.

Kind regards

Adrian

**Comment by rowanmiller** [comment]
Agreed the idea of a global filter would be useful. Popping on the backlog as it is lower priority than some things we are going to tackle first. BTW we have an issue specifically for soft delete (https://github.com/aspnet/EntityFramework/issues/4025), but we also want to track this more general idea.

Regarding EntityFramework-Plus, we have #3736 on our candidate list to address in the 1.1.0 release.

**Comment by julielerman** [comment]
oh what a coincidence that you commented on this just a few minutes ago! I"m trying to use an interface in onmodelcreating and have been looking for workarounds to the requirement that modelbuilder.Entity requies a reference type and won't accept an interface.  Any temporary workarounds that you know of? Thanks

**Comment by julielerman** [comment]
this is my sad little magic string, not type-checked, workaround:
foreach (var entity in modelBuilder.Model.GetEntityTypes()) {
      
        modelBuilder.Entity(entity.Name).Ignore("thenonmappedproperty");
      }

modelBuilder.Entity<IFancyType>().Ignore(p=>p.thenonmappedproperty)

But okay for my purposes for the time being. :)

**Comment by AdrianHostettler** [comment]
Hy guys, thx for the infos and hints.

My focus isn't on the softdeletion topic, it's more an example of a usecase (like DateCreated/DateModified) for the Filter request.

I've got a working softdeletion implementation by overwriting OnSaveChanges now, but since you both are referring to the shadow properties, i'm wondering if shadow props would be a 'cleaner' approach than overwriting OnSaveChanges.

As I understand the **Pros** for "shadow props" over "OnSaveChanges Overwriting" would be, that i don't have to implement the same interface on every model, and would have still access to the properties over the "not type-checked" way, as @julielerman describes it in her last comment. So the "not type-checked" way would in that aspect still be a little **Con** over the "OnSaveChanges" approach.

@julielerman I grew fond of your pluralsight vids the last half year, and so I'm wondering to which approach your experienced guts would tend to?

**Comment by anpete** [comment]
Addressed in b1379b10f

**Comment by hikalkan** [comment]
Is there any documentation for that?

**Comment by HappyNomad** [comment]
> Such filters are automatically applied by the query compiler to any query targeting the corresponding EntityType.

To clarify, the filters are also applied to types deriving from `EntityType`, right?

**Comment by divega** [comment]
@hikalkan we still have a lot of work to do in documenting 2.0 features. There is a simple example in the [announcement blog post](https://blogs.msdn.microsoft.com/dotnet/2017/05/12/announcing-ef-core-2-0-preview-1/).

@HappyNomad that is correct. The only limitation AFAIK is that the filter can only be defined over the base type on a hierarchy.

**Comment by HappyNomad** [comment]
Do shadow properties work in this context?  I'd like to write:

    modelBuilder.Entity<Account>().HasQueryFilter( a => EF.Property<int>( a, "tenantID" ) == TenantID );

If not, where's the issue for this or do I need to create it?

**Comment by anpete** [comment]
@HappyNomad Yep, that should work.

**Comment by HappyNomad** [comment]
The [What's New doc](https://docs.microsoft.com/en-us/ef/core/what-is-new/) says,

> Limitations
> - Navigation references are not allowed. This feature may be added based on feedback.
> - Filters can only be defined on the root Entity Type of a hierarchy

The first limitation says "This feature may be added based on feedback.", and I found #8881 covers it.  The second limitation doesn't say that.  Does that mean that limitation will likely never be removed?  Or is there at least an issue that covers it?

I ask for planning purposes.  If this situation will likely never change then I can design my domain model with persisted properties that are a generalization of `IsDeleted`, or perhaps the inverse `IsActive`.  I'd work around the limitations by calculating the query result in memory, and persisting the entity with it, rather than using `HasQueryFilter` to query that value later.

Alternatively, it seems I could partially get around the second limitation by writing:

    HasQueryFilter( a => !(a is Subclass && a.IsFoo) )

Will this work?  (I haven't been able to confirm yet due to strange errors.)  What about accessing a property on the subclass like the following?

    HasQueryFilter( a => !(a is Subclass && a.IsFoo && ((Subclass)a).IsBar) )

When I tried this, I get the error, "No coercion operator is defined between types" where one type isn't even mentioned in the expression.  It would be great if it does work, but removing the second limitation would still allow nicer syntax.

**Comment by HappyNomad** [comment]
And another question...  This one has high practical importance to me, so I really hope to get an answer.

Can I, and how would I, construct a filter (that actually works) like the following:

	modelBuilder.Entity<Thing>().HasQueryFilter( t =>
		Orgs.Single( o => o.ID == TenantID ).PurchasedNames.Split( new char[] { ',' } ).Contains( t.Name )
	);

**Comment by smitpatel** [comment]
If that filter is not using navigation path then it would just work.
