### ISSUE TITLE
Chaining where clauses creates 1000ths of queries

### ISSUE THREAD

**Issue by nfdevil** [aspnet/EntityFramework#6448]
### Steps to reproduce
The LINQ-to-SQL code:
``` C#
_context.Patienten.Include(p => p.Dossiers).ThenInclude(d => d.DossierContact).ThenInclude(dc => dc.Verpleegperiodes)
                .Where(p =>
                    p.Dossiers.Any(d =>
                            d.DossierContact.Verpleegperiodes.Any(date =>
                                (!date.BeginDatumUur.HasValue || date.BeginDatumUur.Value <= datetime) &&
                                (!date.BeginDatumUur.HasValue || date.EindDatumUur.Value >= datetime))
                    )).Where(p =>
                    p.Dossiers.Any(d => d.DossierContact == null ||
                        d.DossierContact.Verpleegperiodes.Any(vp =>
                            !vp.BeginDatumUur.HasValue || vp.BeginDatumUur.Value.Year.ToString() == "2015"))).Count()
```

[The files on a public Gist](https://gist.github.com/nfdevil/9a43ccd0ceb5d2ffd387b1c82e5a560d)

Relationships defined in the DbEntityConfiguration's: Patient 1-to-many Dossiers, Dossier one-to-one DossierContact, DossierContact 1-to-many Verpleegperiodes.

### The issue
I have a piece of code that I'm trying to port from EF6 to EF core (in an ASP.NET core 1.0 RTM project). It filters the patients table for all patients with a datetime between the "Verpleegperiode" startdate and enddate and for example with a "Verpleegperiode" in the year 2015. (I used this in my EF6 project to create dynamic filters by adding Where clauses to the IQueryable object, to filter on name, birthdate, and these kind of filters).

This results in a query being called for each "Verpleegperiode" in each "Dossier's" "DossierContact". Since there are over 50000 records in each table, this keeps on going and never finishes the query (probably takes hours ...)

In EF6, this generated a query with both Where clauses in 1 and using joins and subqueries automatically created by EF6 and worked.

I am not sure that this is something that isn't finished in EF core, or that this is a fault in my code.
[I've asked this on StackOverflow yesterday](http://stackoverflow.com/questions/39248809/ef-core-1-0-0-chaining-where-clauses).

~~If you are seeing an exception, include the full exceptions details (message and stack trace).~~

~~Exception message:~~
~~Stack trace:~~

### Further technical details

EF Core version: (found in project.json or packages.config)   
`"Microsoft.EntityFrameworkCore": "1.0.0"`
`"Microsoft.EntityFrameworkCore.SqlServer": "1.0.0"`

Operating system: Windows 8.1/Windows Server 2012 (tested on both my pc and our server)
Visual Studio version: (e.g. VS 2013 or n/a) VS 2015 Professional Update 3

The logs of the query:
![Screen1](https://cloud.githubusercontent.com/assets/7434048/18157338/0d27009c-701d-11e6-9b2a-56a42944f212.PNG)
![Screen2](https://cloud.githubusercontent.com/assets/7434048/18157340/0e89346e-701d-11e6-8f75-e9048fcc02a3.PNG) these small queries keep on being created 1000ths of times.

**Comment by gdoron** [comment]
You should probably check the nightly builds.
I believe the issue was fixed in 1.1.0 already (wasn't released yet)

**Comment by gdoron** [comment]
But I found out, that complicated queries usually it's much better writing them in raw SQL.
Check FromSql.

**Comment by maumar** [comment]
@nfdevil can you also provide configuration for your model? (it's missing from the gist). Also one thing you can try right away is remove call to ToString() in your last predicate. EF doesn't know how to translate this to SQL so it forces (more) evaluation on the client. You can do:

```cs
vp.BeginDatumUur.Value.Year == 2015
```

instead

**Comment by maumar** [comment]
Also, you don't need those Includes at the start of the query, EF will figure out which navigations it needs based on the rest of the query. You only need includes if you project actual entities and want to access their navigations on the client later. In your current query they are being ignored.

**Comment by nfdevil** [comment]
@maumar thanks for the heads-up on the includes. I was reading about the Eager loading not being implemented yet, so I was thinking it meant that when you use a navigation property in a Where clause, you had to 'Include' those navigations.

I've added the configuration files to the gist.

Removing the ToString() did not solve the problem.

@gdoron I've tried using the nightlies, but since it's a pretty big solutionfile, this gave alot of errors with the depencencies, so I guess I'll wait for the release of the 1.1.0 before continuing with the project.

**Comment by Tasteful** [comment]
Checkout #5117 that have the discussion about evaluate untranslatable queries on the client that is causing the multiple executions.

**Comment by maumar** [comment]
This works now, most likely fixed by 757e6d4b1bcdad9e4831321edb9ecf42f4007fbd

Currently the query that is produced is as follows:

```sql
SELECT COUNT(*)
FROM [Patient] AS [p]
WHERE EXISTS (
    SELECT 1
    FROM [Dossier] AS [d]
    LEFT JOIN [DossierContact] AS [d.DossierContact] ON [d].[DossierId] = [d.DossierContact].[DossierId]
    WHERE EXISTS (
        SELECT 1
        FROM [Verpleegperiodes] AS [date]
        WHERE (([date].[BeginDatumUur] IS NULL OR ([date].[BeginDatumUur] <= @__datetime_0)) AND ([date].[BeginDatumUur] IS NULL OR ([date].[EindDatumUur] >= @__datetime_1))) AND ([d.DossierContact].[DossierContactId] = [date].[DossierContactId])) AND ([p].[PatientId] = [d].[PatientId])) AND EXISTS (
    SELECT 1
    FROM [Dossier] AS [d0]
    LEFT JOIN [DossierContact] AS [d.DossierContact1] ON [d0].[DossierId] = [d.DossierContact1].[DossierId]
    WHERE ([d.DossierContact1].[DossierContactId] IS NULL OR EXISTS (
        SELECT 1
        FROM [Verpleegperiodes] AS [vp]
        WHERE ([vp].[BeginDatumUur] IS NULL OR (DATEPART(year, [vp].[BeginDatumUur]) = 2015)) AND ([d.DossierContact1].[DossierContactId] = [vp].[DossierContactId]))) AND ([p].[PatientId] = [d0].[PatientId]))
```
